#!/usr/bin/env node
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
if (process.env.NODE_ENV === 'development') require('babel-register');

const program = require('commander');

let cron;
let main;
program
  .version('0.0.1')
  .usage('<cmd> [options]')
  .arguments('<cmd> [command]')
  .action((cmd, command = 'main') => ([cron, main] = [cmd, command]))
  .option('-c, --count [maxJobCount]', 'Add the number of jobs to parse')
  .parse(process.argv);

if (!cron) {
  program.outputHelp();
  process.exit(1);
}

process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
  // application specific logging, throwing an error, or other logic here
});

process.on('uncaughtException', (err) => {
  console.log('uncaughtException', err);
});

let Task;
const count = `${program.count}`;

if(count !== 'undefined'){
  Task = require(`./server/crons/${cron}`)(count);
} else {
  Task = require(`./server/crons/${cron}`);
}

