const packageItems = [{
  id: 9,
  name: 'Hello Box',
  quantity: 2,
  price_amount: 2,
  total_amount: 4,
  object: 'https://staging-cdn.shoppre.com/shoppre/2018/6/8a854b15-7cc5-4553-b8ae-a6fd49fe89ee.png',
  package_item_category_id: 18,
  PackageItemCategory: {
    name: 'Good Category',
  },
  package_id: '10',
  created_by: 1,
}];

const OPS = {
  id: 1,
  first_name: 'Saneel',
  last_name: 'E S',
  email: 'support@shoppre.com',
};

const pkg = {
  id: 1,
  invoice_code: 'AMZ123',
  Store: {
    name: 'Amazon.in',
  },
  created_at: '19-07-2018',
  price_amount: '250',
  total_quantity: '2',
};

const customer = {
  id: 646,
  name: 'Mr. Abhinav Mishra',
  first_name: 'Abhinav',
  virtual_address_code: 'SHPR12-182',
  email: 'tech.shoppre@shoppre.com',
  phone: 9071032646,
};

const ENV = {
  URLS_PARCEL: 'http://parcel.shoppre.test',
  URLS_WWW: 'http://www.shoppre.test',
  URLS_MYACCOUNT: 'http://myaccount.shoppre.test',
};

module.exports = {
  PACKAGE_ITEMS_UPLOAD_PENDING: {
    PACKAGE_ITEMS_UPLOAD_PENDING: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    subject: 'Your Package Has Just Arrived at Our Facility!',
  },
  CUSTOMER_INPUT: {
    CUSTOMER_INPUT: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: 'Please Input the Product Costs of Your Purchase',
  },
  READY_TO_SHIP: {
    READY_TO_SHIP: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: `Your Package Is Ready to be Shipped | Package ID: ${pkg.id}`,
  },
  DAMAGED: {
    DAMAGED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: 'Seems Your Item Had Arrived Here With a Damage!',
  },
  RETURN_REQUEST_FROM_CUSTOMER: {
    RETURN_REQUEST_FROM_CUSTOMER: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: `Your Request to Return the Package ID: ${pkg.id} Has Been Received`,
  },
  RETURN_PICKUP_DONE: {
    RETURN_PICKUP_DONE: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: `Return Request | Your Package ID: ${pkg.id}Has Been Dispatched `,
  },
  UPLOAD_INVOICE_REQUESTED: {
    UPLOAD_INVOICE_REQUESTED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: 'Please Upload the Invoice of Your Purchase',
  },
  SPLIT_PACKAGE: {
    SPLIT_PACKAGE: true,
    nextStateName: 'SPLIT_PACKAGE',
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: 'Request to Split Your Package Has Been Received',
  },
  SPLIT_PACKAGE_PROCESSED: {
    SPLIT_PACKAGE_PROCESSED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: `Your Package ID: ${pkg.id} has successfully been split!`,
  },
  DISCARDED: {
    DISCARDED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: `Your Package ID: ${pkg.id} Has Successfully Been Discarded!`,
  },
  DISCARD_REQUESTED: {
    DISCARD_REQUESTED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: `Your Request to Discard the Package ID: ${pkg.id} Has Been Received`,
  },
  STANDARD_PHOTO_REQUEST: {
    STANDARD_PHOTO_REQUEST: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: 'Customer Has Requested Standard Photos',
  },
  ADVANCED_PHOTO_REQUEST: {
    ADVANCED_PHOTO_REQUEST: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: 'Customer Has Requested Advanced Photos',
  },
  PS_RETURN_REQUESTED: {
    PS_RETURN_REQUESTED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  PS_REFUND_RECIEVED: {
    PS_REFUND_RECIEVED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  ORDER_CREATED: {
    ORDER_CREATED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  ORDER_CANCELLED: {
    ORDER_CANCELLED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  PAYMENT_INITIATED: {
    PAYMENT_INITIATED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  PAYMENT_FAILED: {
    PAYMENT_FAILED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  PAYMENT_COMPLETED: {
    PAYMENT_COMPLETED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  ORDER_PLACED: {
    ORDER_PLACED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  OUT_OF_STOCK: {
    OUT_OF_STOCK: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  REFUNDED_TO_WALLET: {
    REFUNDED_TO_WALLET: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  REFUNDED_TO_BANK_ACCOUNT: {
    REFUNDED_TO_BANK_ACCOUNT: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
  AWAITING_PACKAGE: {
    AWAITING_PACKAGE: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
    subject: '',
  },
};
