module.exports = ({
  nextStateName, pkg, targetUser, paymentGateway,
}) => ({
  PACKAGE_ITEMS_UPLOAD_PENDING: 'Your Package Has Just Arrived at Our Facility!',
  CUSTOMER_INPUT: 'Please Input the Product Costs of Your Purchase',
  READY_TO_SHIP: `Your Package Is Ready to be Shipped | Package ID: ${pkg.id}`,
  DAMAGED: 'Seems Your Item Had Arrived Here With a Damage!',
  RETURN_REQUEST_FROM_CUSTOMER: `Your Request to Return the Package ID: ${pkg.id} Has Been Received`,

  RETURN_PICKUP_DONE: `Return Request | Your Package ID: ${pkg.id} Has Been Dispatched `,
  SPLIT_PACKAGE: 'Request to Split Your Package Has Been Received',
  SPLIT_PACKAGE_PROCESSED: 'Your Package ID has successfully been split!',
  UPLOAD_INVOICE_REQUESTED: 'Please Upload the Invoice of Your Purchase',
  DISCARD_REQUESTED: `Your Request to Discard the Package ID: ${pkg.id} Has Been Received`,
  DISCARDED: `Your Package ID: ${pkg.id} Has Successfully Been Discarded! `,
  STANDARD_PHOTO_REQUEST: '',
  ADVANCED_PHOTO_REQUEST: targetUser.MEMBER === 'MEMBER' ? 'We Have Received Your Request for Advanced Photos' : 'Customer Has Requested Advanced Photos',
  PS_RETURN_REQUESTED: '',
  PS_REFUND_RECIEVED: '',
  PAYMENT_COMPLETED: `You have Chosen to Pay via ${paymentGateway.name} |Order ${pkg.order_code} Created`,
  ORDER_CANCELLED: `Your Personal Shopper Order ${pkg.id} Has Been Cancelled`,
  PRICE_CHANGED: 'Item(s) Have changed Price',
  PAYMENT_FAILED: `Transaction Attempt Failed: Using your ${paymentGateway.name} | Order ID: ${pkg.order_code}`,
  PAYMENT_CONFIRMED: `We Have Received Your Payment on Personal Shopper Order ${pkg.order_code}`,
  ORDER_PLACED: 'We Have Successfully Placed Your Order',
  OUT_OF_STOCK: 'Item(s) Have Went Out of Stock',
  REFUNDED_TO_WALLET: `We've Finished Refunding Your Payment for the Order ${pkg.order_code}`,
  REFUNDED_TO_BANK_ACCOUNT: `We've Finished Refunding Your Payment for the Order ${pkg.order_code}`,
  ORDER_COMPLETED: `All Items on Your Personal Shopper Order ${pkg.order_code} Have Arrived`,
  AWAITING_PACKAGE: '',
  PACKAGE_STORAGE: 'FREE storage is about to expire! Request to Ship soon!',
  PACKAGE_STORAGE_EXCEEDED: 'FREE storage has expired! Request to ship immediately!',
}[nextStateName]);
