module.exports = ({ nextStateName, pkg, targetUser }) => ({
  PACKAGE_ITEMS_UPLOAD_PENDING: 'Your Package Has Just Arrived at Our Facility!',
  CUSTOMER_INPUT: 'Please Input the Product Costs of Your Purchase',
  READY_TO_SHIP: `Your Package Is Ready to be Shipped | Package ID: ${pkg.id}`,
  DAMAGED: 'Seems Your Item Had Arrived Here With a Damage!',
  RETURN_REQUEST_FROM_CUSTOMER: `Your Request to Return the Package ID: ${pkg.id} Has Been Received`,

  RETURN_PICKUP_DONE: `Return Request | Your Package ID: ${pkg.id} Has Been Dispatched `,
  SPLIT_PACKAGE: 'Request to Split Your Package Has Been Received',
  SPLIT_PACKAGE_PROCESSED: 'Your Package ID has successfully been split!',
  UPLOAD_INVOICE_REQUESTED: 'Please Upload the Invoice of Your Purchase',
  DISCARD_REQUESTED: `Your Request to Discard the Package ID: ${pkg.id} Has Been Received`,
  DISCARDED: `Your Package ID: ${pkg.id} Has Successfully Been Discarded! `,
  STANDARD_PHOTO_REQUEST: '',
  ADVANCED_PHOTO_REQUEST: targetUser.MEMBER === 'MEMBER' ? 'We Have Received Your Request for Advanced Photos' : 'Customer Has Requested Advanced Photos',
  PS_RETURN_REQUESTED: '',
  PS_REFUND_RECIEVED: '',
  ORDER_CREATED: '',
  ORDER_CANCELLED: '',
  PAYMENT_INITIATED: '',
  PAYMENT_FAILED: '',
  PAYMENT_COMPLETED: '',
  ORDER_PLACED: '',
  OUT_OF_STOCK: '',
  REFUNDED_TO_WALLET: '',
  REFUNDED_TO_BANK_ACCOUNT: '',
  AWAITING_PACKAGE: '',
}[nextStateName]);
