pipeline:
  build:
    image: node:8.11
    commands:
      - pwd
      - ls
      - git log --oneline -n 5
      - npm -v
      - node -v
      - npm install
      - cp .env.sample .env
      - npm run clear-db
      - npm run migrate
      - npm run login
      - npm test
      - COVERALLS_REPO_TOKEN=WDamv9hmwlD9xelfrA9TBSZkwVglMXQ3n
      - npm run coverage
