
const shipmentDetails = {
  id: 9,
  order_code: 'DH6677889',
  customer_name: 'MEENA',
  address: 2,
  phone: 789890082990,
  packages_count: 5,
  final_weight: 10,
  estimated_amount: '7000',
  final_amount: '10000',
  created_by: 1,
  tracking_code: '1234567H',
  shipping_carrier: 'DHL',
  dispatch_date: '2018-08-20',
};

const paymentGateway = {
  name: 'wire',
};

const OPS = {
  first_name: 'Saneel',
  last_name: 'E S',
  email: 'support@shoppre.com',
};

const pkg = [{
  id: 1,
  invoice_code: 'AMZ123',
  order_code: 'PKG123',
  Store: {
    name: 'Amazon',
  },
  weight: 1,
  tracking_number: 'A123GGH',
  created_at: '2018-08-20',
}];

const shipToAddress = {
  line1: '314 Euphoria Circle',
  line2: '314 Euphoria Circle',
  city: 'Cary, NC',
  state: 'florida',
  country: 'United states',
  pincode: '560008',
  phone: '8970972343',
};

const customer = {
  name: 'Mr. Abhinav Mishra',
  first_name: 'Abhinav',
  virtual_address_code: 'SHPR12-182',
  email: 'support@shoppre.com',
};

const ENV = {
  URLS_MEMBER: 'http://member.shoppre.test',
  URLS_WWW: 'http://www.shoppre.test',
};

module.exports = {
  PACKAGING_REQUESTED: {
    PACKAGING_REQUESTED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
  },
  INVOICE_REQUESTED: {
    INVOICE_REQUESTED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  PAYMENT_REQUESTED: {
    PAYMENT_REQUESTED: true,
    pkg,
    customer,
    actingUser: OPS,
    shipToAddress,
    ENV,
    shipmentDetails,
  },
  PAYMENT_INITIATED: {
    PAYMENT_INITIATED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    shipToAddress,
    shipmentDetails,
  },
  PAYMENT_COMPLETED: {
    PAYMENT_COMPLETED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
    paymentGateway,
  },
  PAYMENT_FAILED: {
    PAYMENT_FAILED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  PAYMENT_CONFIRMED: {
    PAYMENT_CONFIRMED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  UPSTREAM_SHIPMENT_REQUEST_CREATED: {
    UPSTREAM_SHIPMENT_REQUEST_CREATED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  SHIPMENT_HANDED: {
    SHIPMENT_HANDED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  SHIPMENT_IN_TRANSIT: {
    SHIPMENT_IN_TRANSIT: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  SHIPMENT_MANUAL_FOLLOW_UP: {
    SHIPMENT_MANUAL_FOLLOW_UP: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  SHIPMENT_LOST: {
    SHIPMENT_LOST: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  CUSTOM_ON_HOLD: {
    CUSTOM_ON_HOLD: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  WRONG_ADDRESS: {
    WRONG_ADDRESS: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  SHIPMENT_REJECTED_BY_CUSTOMER: {
    SHIPMENT_REJECTED_BY_CUSTOMER: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  RTO_REQUESTED: {
    RTO_REQUESTED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  RAISE_SHIPMENT_LOST_CLAIM: {
    RAISE_SHIPMENT_LOST_CLAIM: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  PENALTY_PAYMENT_REQUESTED: {
    PENALTY_PAYMENT_REQUESTED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  RETURN_TO_ORIGIN: {
    RETURN_TO_ORIGIN: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  AMOUNT_RECEIVED_FROM_UPSTREAM: {
    AMOUNT_RECEIVED_FROM_UPSTREAM: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  PENALTY_PAYMENT_DONE: {
    PENALTY_PAYMENT_DONE: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  WRONG_ADDRESS_FOLLOW_UP: {
    WRONG_ADDRESS_FOLLOW_UP: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  CLAIM_PROCESSED_TO_CUSTOMER: {
    CLAIM_PROCESSED_TO_CUSTOMER: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  CUSTOMER_ACKNOWLEDGEMENT_RECEIVED: {
    CUSTOMER_ACKNOWLEDGEMENT_RECEIVED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  SHIPMENT_DELIVERED: {
    SHIPMENT_DELIVERED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
  SHIPMENT_CANCELLED: {
    SHIPMENT_CANCELLED: true,
    pkg,
    customer,
    shipToAddress,
    actingUser: OPS,
    ENV,
    shipmentDetails,
  },
};
