module.exports = {
  PACKAGE: {
    RETURN: 400,
    STANDARD_PHOTO: 20,
    ADVANCED_PHOTO: 500,
    SPLIT_PACKAGE: 200,
    PERSONAL_SHOPPER_PERCENTAGE: 7,
    PACKAGE_STORAGE_EXCEEDED_CHARGE: 100,
    SELF_SHOPPER_PERCENTAGE: 10,
  },
  SHIPMENT: { PAYMENT_DELAY_EXCEEDED_CHARGE: 100 },
};
