
module.exports = () => [{
  id: 1,
  repack: '1',
  is_liquid: '1',
  repacking_charge_amount: 100,
  sticker: '1',
  sticker_charge_amount: 100,
  extra_packing: '0',
  extra_packing_charge_amount: 0,
  original: '0',
  original_ship_box_charge__amount: 0,
  max_weight: 1.5,
  consolidation: '0',
  consolidation_charge_amount: 0,
  gift_wrap: '0',
  gift_wrap_charge_amount: 0,
  gift_note: '0',
  gift_note_charge_amount: 0,
  shipment_id: 115,

}, {
  id: 2,
  repack: '1',
  is_liquid: '0',
  repacking_charge_amount: 100,
  sticker: '1',
  sticker_charge_amount: 100,
  extra_packing: '0',
  extra_packing_charge_amount: 0,
  original: '0',
  original_ship_box_charge__amount: 0,
  max_weight: 1.5,
  consolidation: '0',
  consolidation_charge_amount: 0,
  gift_wrap: '0',
  gift_wrap_charge_amount: 0,
  gift_note: '0',
  gift_note_charge_amount: 0,
  shipment_id: 116,
}];
