module.exports = () => [
  {
    id: '1',
    user_id: null,
    parent_id: 1,
    name: 'Africa',
    slug: 'africa',
    alias: null,
    type: 'continent',
    ref_id: '1',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '2',
    user_id: null,
    parent_id: 1,
    name: 'Antarctica',
    slug: 'antarctica',
    alias: null,
    type: 'continent',
    ref_id: '2',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '3',
    user_id: null,
    parent_id: 1,
    name: 'Asia',
    slug: 'asia',
    alias: null,
    type: 'continent',
    ref_id: '3',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '4',
    user_id: null,
    parent_id: 1,
    name: 'Europe',
    slug: 'europe',
    alias: null,
    type: 'continent',
    ref_id: '4',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '5',
    user_id: null,
    parent_id: 1,
    name: 'North America',
    slug: 'north-america',
    alias: null,
    type: 'continent',
    ref_id: '5',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '6',
    user_id: null,
    parent_id: 1,
    name: 'Oceania',
    slug: 'oceania',
    alias: null,
    type: 'continent',
    ref_id: '6',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '7',
    user_id: null,
    parent_id: 1,
    name: 'South America',
    slug: 'south-america',
    alias: null,
    type: 'continent',
    ref_id: '7',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '8',
    user_id: null,
    parent_id: 1,
    name: 'Americas',
    slug: 'americas',
    alias: null,
    type: 'continent',
    ref_id: '8',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '74',
    user_id: null,
    parent_id: '3',
    name: 'Georgia',
    slug: 'georgia',
    alias: null,
    type: 'country',
    ref_id: '1',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '75',
    user_id: null,
    parent_id: '3',
    name: 'Afghanistan',
    slug: 'afghanistan',
    alias: null,
    type: 'country',
    ref_id: '2',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '76',
    user_id: null,
    parent_id: '3',
    name: 'Armenia',
    slug: 'armenia',
    alias: null,
    type: 'country',
    ref_id: '13',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '77',
    user_id: null,
    parent_id: '3',
    name: 'Azerbaijan',
    slug: 'azerbaijan',
    alias: null,
    type: 'country',
    ref_id: '17',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '78',
    user_id: null,
    parent_id: '3',
    name: 'Bahrain',
    slug: 'bahrain',
    alias: null,
    type: 'country',
    ref_id: '21',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '79',
    user_id: null,
    parent_id: '3',
    name: 'Bangladesh',
    slug: 'bangladesh',
    alias: null,
    type: 'country',
    ref_id: '22',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '80',
    user_id: null,
    parent_id: '3',
    name: 'Bhutan',
    slug: 'bhutan',
    alias: null,
    type: 'country',
    ref_id: '29',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '81',
    user_id: null,
    parent_id: '3',
    name: 'Brunei Darussalam',
    slug: 'brunei-darussalam',
    alias: null,
    type: 'country',
    ref_id: '36',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '82',
    user_id: null,
    parent_id: '3',
    name: 'Cambodia',
    slug: 'cambodia',
    alias: null,
    type: 'country',
    ref_id: '40',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '83',
    user_id: null,
    parent_id: '3',
    name: 'China',
    slug: 'china',
    alias: null,
    type: 'country',
    ref_id: '48',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '84',
    user_id: null,
    parent_id: '3',
    name: 'Cyprus',
    slug: 'cyprus',
    alias: null,
    type: 'country',
    ref_id: '60',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '85',
    user_id: null,
    parent_id: '3',
    name: 'Hong Kong',
    slug: 'hong-kong',
    alias: null,
    type: 'country',
    ref_id: '102',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '86',
    user_id: null,
    parent_id: '3',
    name: 'India',
    slug: 'india',
    alias: null,
    type: 'country',
    ref_id: '105',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '87',
    user_id: null,
    parent_id: '3',
    name: 'Indonesia',
    slug: 'indonesia',
    alias: null,
    type: 'country',
    ref_id: '106',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '88',
    user_id: null,
    parent_id: '3',
    name: 'Iran, Islamic Republic Of',
    slug: 'iran-islamic-republic-of',
    alias: null,
    type: 'country',
    ref_id: '107',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '89',
    user_id: null,
    parent_id: '3',
    name: 'Iraq',
    slug: 'iraq',
    alias: null,
    type: 'country',
    ref_id: '108',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '90',
    user_id: null,
    parent_id: '3',
    name: 'Israel',
    slug: 'israel',
    alias: null,
    type: 'country',
    ref_id: '111',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '91',
    user_id: null,
    parent_id: '3',
    name: 'Japan',
    slug: 'japan',
    alias: null,
    type: 'country',
    ref_id: '114',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '92',
    user_id: null,
    parent_id: '3',
    name: 'Jordan',
    slug: 'jordan',
    alias: null,
    type: 'country',
    ref_id: '116',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '93',
    user_id: null,
    parent_id: '3',
    name: 'Kazakhstan',
    slug: 'kazakhstan',
    alias: null,
    type: 'country',
    ref_id: '117',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '94',
    user_id: null,
    parent_id: '3',
    name: 'Korea, Republic of',
    slug: 'korea-republic-of',
    alias: null,
    type: 'country',
    ref_id: '120',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '95',
    user_id: null,
    parent_id: '3',
    name: "Korea, Democratic People's Republic Of",
    slug: 'korea-democratic-peoples-republic-of',
    alias: null,
    type: 'country',
    ref_id: '121',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '96',
    user_id: null,
    parent_id: '3',
    name: 'Kuwait',
    slug: 'kuwait',
    alias: null,
    type: 'country',
    ref_id: '122',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '97',
    user_id: null,
    parent_id: '3',
    name: 'Kyrgyzstan',
    slug: 'kyrgyzstan',
    alias: null,
    type: 'country',
    ref_id: '123',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '98',
    user_id: null,
    parent_id: '3',
    name: "Lao People's Democratic Republic",
    slug: 'lao-peoples-democratic-republic',
    alias: null,
    type: 'country',
    ref_id: '124',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  },
  {
    id: '1947',
    user_id: null,
    parent_id: '86',
    name: 'Karnataka',
    slug: 'karnataka',
    alias: null,
    type: 'state',
    ref_id: '1677',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',
  }, {
    id: '8705',
    user_id: null,
    parent_id: '1947',
    name: 'Bagalkot',
    slug: 'bagalkot',
    alias: null,
    type: 'district',
    ref_id: '244',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8706',
    user_id: null,
    parent_id: '1947',
    name: 'Bangalore Rural',
    slug: 'bangalore-rural',
    alias: null,
    type: 'district',
    ref_id: '245',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8707',
    user_id: null,
    parent_id: '1947',
    name: 'Bangalore',
    slug: 'bangalore',
    alias: null,
    type: 'district',
    ref_id: '246',
    metro: '1',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8708',
    user_id: null,
    parent_id: '1947',
    name: 'Belgaum',
    slug: 'belgaum',
    alias: null,
    type: 'district',
    ref_id: '247',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8709',
    user_id: null,
    parent_id: '1947',
    name: 'Bellary',
    slug: 'bellary',
    alias: null,
    type: 'district',
    ref_id: '248',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8710',
    user_id: null,
    parent_id: '1947',
    name: 'Bidar',
    slug: 'bidar',
    alias: null,
    type: 'district',
    ref_id: '249',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8711',
    user_id: null,
    parent_id: '1947',
    name: 'Bijapur',
    slug: 'bijapur',
    alias: null,
    type: 'district',
    ref_id: '250',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8712',
    user_id: null,
    parent_id: '1947',
    name: 'Chamarajnagar',
    slug: 'chamarajnagar',
    alias: null,
    type: 'district',
    ref_id: '251',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8713',
    user_id: null,
    parent_id: '1947',
    name: 'Chikkamagaluru',
    slug: 'chikkamagaluru',
    alias: null,
    type: 'district',
    ref_id: '252',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8714',
    user_id: null,
    parent_id: '1947',
    name: 'Chikkaballapur',
    slug: 'chikkaballapur',
    alias: null,
    type: 'district',
    ref_id: '253',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8715',
    user_id: null,
    parent_id: '1947',
    name: 'Chitradurga',
    slug: 'chitradurga',
    alias: null,
    type: 'district',
    ref_id: '254',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8716',
    user_id: null,
    parent_id: '1947',
    name: 'Davanagere',
    slug: 'davanagere',
    alias: null,
    type: 'district',
    ref_id: '255',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8717',
    user_id: null,
    parent_id: '1947',
    name: 'Dharwad',
    slug: 'dharwad',
    alias: null,
    type: 'district',
    ref_id: '256',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8718',
    user_id: null,
    parent_id: '1947',
    name: 'Dakshina Kannada',
    slug: 'dakshina-kannada',
    alias: null,
    type: 'district',
    ref_id: '257',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8719',
    user_id: null,
    parent_id: '1947',
    name: 'Gadag',
    slug: 'gadag',
    alias: null,
    type: 'district',
    ref_id: '258',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8720',
    user_id: null,
    parent_id: '1947',
    name: 'Gulbarga',
    slug: 'gulbarga',
    alias: null,
    type: 'district',
    ref_id: '259',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8721',
    user_id: null,
    parent_id: '1947',
    name: 'Hassan',
    slug: 'hassan',
    alias: null,
    type: 'district',
    ref_id: '260',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8722',
    user_id: null,
    parent_id: '1947',
    name: 'Haveri district',
    slug: 'haveri-district',
    alias: null,
    type: 'district',
    ref_id: '261',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8723',
    user_id: null,
    parent_id: '1947',
    name: 'Kodagu',
    slug: 'kodagu',
    alias: null,
    type: 'district',
    ref_id: '262',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8724',
    user_id: null,
    parent_id: '1947',
    name: 'Kolar',
    slug: 'kolar',
    alias: null,
    type: 'district',
    ref_id: '263',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8725',
    user_id: null,
    parent_id: '1947',
    name: 'Koppal',
    slug: 'koppal',
    alias: null,
    type: 'district',
    ref_id: '264',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8726',
    user_id: null,
    parent_id: '1947',
    name: 'Mandya',
    slug: 'mandya',
    alias: null,
    type: 'district',
    ref_id: '265',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8727',
    user_id: null,
    parent_id: '1947',
    name: 'Mysore',
    slug: 'mysore',
    alias: null,
    type: 'district',
    ref_id: '266',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8728',
    user_id: null,
    parent_id: '1947',
    name: 'Raichur',
    slug: 'raichur',
    alias: null,
    type: 'district',
    ref_id: '267',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  }, {
    id: '8729',
    user_id: null,
    parent_id: '1947',
    name: 'Shimoga',
    slug: 'shimoga',
    alias: null,
    type: 'district',
    ref_id: '268',
    metro: '0',
    latitude: null,
    longitude: null,
    verified: '1',


  },
];
