module.exports = (sequelize, DataTypes) => {
  const SchedulePickup = sequelize.define('SchedulePickup', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    first_name: DataTypes.STRING,
    last_name: DataTypes.STRING,
    user_email: DataTypes.STRING,
    phone_code: DataTypes.STRING,
    mobile: DataTypes.STRING,
    pickup_address: DataTypes.STRING,
    dest_address: DataTypes.STRING,
    no_of_packages: DataTypes.INTEGER,
    package_weight: DataTypes.DECIMAL(10, 2),
    size_of_package: DataTypes.STRING,
    package_items: DataTypes.STRING,
    special_items: DataTypes.STRING,
    other_items: DataTypes.STRING,
    payment_option: DataTypes.STRING,
    pc_fname: DataTypes.STRING,
    pc_lname: DataTypes.STRING,
    pc_street: DataTypes.STRING,
    pc_pincode: DataTypes.STRING,
    pc_city: DataTypes.STRING,
    pc_state: DataTypes.STRING,
    pc_contact_no: DataTypes.STRING,
    pc_email: DataTypes.STRING,
    dc_fname: DataTypes.STRING,
    dc_lname: DataTypes.STRING,
    dc_street: DataTypes.STRING,
    dc_state: DataTypes.STRING,
    dc_city: DataTypes.STRING,
    dc_country: DataTypes.STRING,
    dc_pincode: DataTypes.STRING,
    dc_phone_code: DataTypes.STRING,
    dc_contact_no: DataTypes.STRING,
    comment: DataTypes.STRING,
    is_admin_read: DataTypes.STRING,
    status: DataTypes.STRING,
    action_comment: DataTypes.STRING,
  }, {
    tableName: 'schedule_pickups',
    timestamps: true,
    underscored: true,
  });

  return SchedulePickup;
};

