module.exports = () => [{
  id: '178',
  user_first_name: 'lavakumar',
  user_last_name: 'Sangeetham',
  user_email: 'lava.sangeetham@gmail.com',
  phone_code: '91',
  mobile: '8122733647',
  number_of_packages: '1',
  package_weight: '12.00',
  size_of_package: '50,30,70',
  package_items: '10',
  special_items: 'Home Made Food items,Liquid items,',
  other_items: '',
  payment_option: 'card',
  created_at: '2018-05-20 ',
  updated_at: '2018-05-20 ',
  first_name: 'lavakumar',
  last_name: 'Sangeetham',
  street: 'Swathanthrapuram  street',
  pincode: '524121',
  city: 'Sullurupeta',
  state: 'Andhra Pradesh',
  contact_no: '8122733647',
  email: 'lava.sangeetham@gmail.com',
  destination_user_first_name: 'kiran kumar',
  destination_user_last_name: 'Kangula',
  destination_street: '711 140, Erskine Avenue',
  destination_state: 'Ontario',
  destination_city: 'Toronto',
  destination_country: 'Canada',
  destination_pincode: 'M4P1Z2',
  destination_phone_code: '1',
  destination_contact_no: '6478333226',
  comment: 'items list:  home made powers (mirchi, turmaric..etc) , Pickles , honey, Ghee',
  is_admin_read: 'no',
  status: 'review',
  action_comment: null,
}, {
  id: '179',
  user_first_name: 'Sushant',
  user_last_name: 'Gupta',
  user_email: 'sushant01g@gmail.com',
  phone_code: '91',
  mobile: '9899027757',
  number_of_packages: '1',
  package_weight: '1.80',
  size_of_package: '',
  package_items: 'T-shirts (Samples)',
  special_items: '',
  other_items: '',
  payment_option: 'shoppre_account',
  created_at: '2018-05-20',
  updated_at: '2018-05-20',
  first_name: 'sushant',
  last_name: 'Gupta',
  street: 'A-2331 SECTOR-8 ROHINI',
  pincode: '110085',
  city: 'New Delhi',
  state: 'Delhi',
  contact_no: '9899027757',
  email: 'sushant01g@gmail.com',
  destination_user_first_name: 'Ingmar',
  destination_user_last_name: 'Kobes',
  destination_street: 'Klein Kromhof Houtvezels B.V.  Daarlerweg 1A , Daarlerveen',
  destination_state: 'Daarlerveen',
  destination_city: 'Daarlerveen',
  destination_country: 'Netherlands, The',
  destination_pincode: '7687 AN',
  destination_phone_code: '31',
  destination_contact_no: '652566655',
  comment: '',
  is_admin_read: 'no',
  status: 'review',
  action_comment: null,
}, {
  id: '180',
  user_first_name: 'asdf',
  user_last_name: 'dsf',
  user_email: 'ppp@gmail.com',
  phone_code: '91',
  mobile: '8970972343',
  number_of_packages: '1',
  package_weight: '1.00',
  size_of_package: '',
  package_items: '1',
  special_items: 'Other,',
  other_items: 'xyz',
  payment_option: 'shoppre_account',
  created_at: '2018-06-05',
  updated_at: '2018-06-05',
  first_name: 'pppp',
  last_name: 'pppp',
  street: 'banglore',
  pincode: '587006',
  city: 'banglore',
  state: 'Karnataka',
  contact_no: '1111111111',
  email: null,
  destination_user_first_name: 'dsfg',
  destination_user_last_name: 'dsfg',
  destination_street: 'banglore',
  destination_state: 'karantaka',
  destination_city: 'banglore',
  destination_country: 'India',
  destination_pincode: 'banglore',
  destination_phone_code: '91',
  destination_contact_no: '8970972343',
  comment: 'dfg',
  is_admin_read: 'no',
  status: 'review',
  action_comment: '',
}];

