
module.exports = (constants) => {
  const {
    GROUP: {
      OPS, MEMBER, MARKETING, MANAGEMENT, FINANCE,
    },
    COUNTRY: {
      IND,
    },
  } = constants;

  return [
    {
      id: 1,
      salutation: 'Mr',
      first_name: 'Saneel',
      last_name: 'E S',
      email: 'support@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: OPS,
    },
    {
      id: 646,
      salutation: 'Mr',
      first_name: 'Abhinav',
      last_name: 'Mishra',
      email: 'tech.shoppre@gmail.com',
      phone_code: '91',
      phone: '9060122213',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: MEMBER,
      virtual_address_code: 'SHPR82-162',
    },
    {
      id: 354,
      salutation: 'Mrs',
      first_name: 'Nikkitha',
      last_name: 'Shanker',
      email: 'nikkitha@shoppre.com',
      phone_code: '91',
      phone: '9844717202',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: MANAGEMENT,
    }, {
      id: 398,
      salutation: 'Ms',
      first_name: 'Vismaya',
      last_name: 'R K',
      email: 'vismaya@shoppre.com',
      phone_code: '91',
      phone: '8921113192',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: MANAGEMENT,
    },
    {
      id: 2940,
      salutation: 'Mr',
      first_name: 'Shoppre',
      last_name: 'Marketing',
      email: 'marketing@shoppre.com',
      phone_code: '91',
      phone: '9844717202',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: MEMBER,
    },
    {
      id: 2177,
      salutation: 'Mr',
      first_name: 'Dhananjaya',
      last_name: 'Shekhar',
      email: 'dj@shoppre.com',
      phone_code: '91',
      phone: '9060122213',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: MARKETING,
    },
    {
      id: 2757,
      salutation: 'Mrs',
      first_name: 'Shilpa',
      last_name: 'Kaimal',
      email: 'shilpa.humcap@gmail.com',
      phone_code: '91',
      phone: '9060122213',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: MEMBER,
    }, {
      id: 129,
      salutation: 'Mr',
      first_name: 'Varun',
      last_name: 'Murali',
      email: 'varun.murali@gmail.com',
      phone_code: '91',
      phone: '585410510',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: MEMBER,
    },
    {
      id: 101,
      salutation: 'Mr',
      first_name: 'Shoppre Agent',
      last_name: 'Bot',
      email: 'bot@shoppre.com',
      phone_code: '91',
      phone: '9844717202',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      country_id: 224,
      created_at: '2016-10-17 19:02:23',
    }, {
      id: 102,
      salutation: 'Mrs',
      first_name: 'Nikkitha',
      last_name: 'Shanker',
      email: 'nikkitha@shoppre.com',
      phone_code: '91',
      phone: '9148359143',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 101,
      created_at: '2016-10-17 19:02:23',
    }, {
      id: 103,
      salutation: 'Ms',
      first_name: 'Saira',
      last_name: 'Hassan',
      email: 'saira@shoppre.com',
      phone_code: '971',
      phone: '501401199',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 102,
      created_at: '2016-10-17 19:02:23',
    }, {
      id: 2309,
      salutation: 'Mrs',
      first_name: 'Swetha',
      last_name: 'Kalkar',
      email: 'swetha@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 102,
      created_at: '2017-10-17 19:02:23',
    }, {
      id: 105,
      salutation: 'Mrs',
      first_name: 'Snehalatha',
      last_name: '',
      email: 'snehalatha@shoppre.com',
      phone_code: '91',
      phone: '9535802244',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 2309,
    }, {
      id: 106,
      salutation: 'Ms',
      first_name: 'Meena',
      last_name: 'Sannapa',
      email: 'meena@shoppre.com',
      phone_code: '91',
      phone: '9071032646',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 2309,
    }, {
      id: 107,
      salutation: 'Ms',
      first_name: 'Prasanna',
      last_name: '',
      email: 'prasanna@shoppre.com',
      phone_code: '91',
      phone: '8977298985',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 105,
    }, {
      id: 108,
      salutation: 'Ms',
      first_name: 'Vismaya',
      last_name: 'R K',
      email: 'vismaya.rk@shoppre.com',
      phone_code: '91',
      phone: '7676323620',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 2309,
    }, {
      id: 109, // marketing
      salutation: 'Ms',
      first_name: 'Manlee',
      last_name: 'Chowdhary',
      email: 'manlee@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 2309,
    }, { // consolidation, Quick Package Entry, Updating Package full details, photo, items
      id: 110,
      salutation: 'Mr',
      first_name: 'Mahesh',
      last_name: 'Krishnamurthy',
      email: 'maheshabvp@icloud.com',
      phone_code: '91',
      phone: '9900759900',
      country_id: 224,
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 102,
    }, { // consolidation, Quick Package Entry, Updating Package full details, photo, items
      id: 111,
      salutation: 'Mr',
      first_name: 'Saneel',
      last_name: 'E S',
      email: 'saneel.es@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 102,
    }, { //  Updating Package full details, photo, items
      id: 112,
      salutation: 'Mr',
      first_name: 'Lakshmi',
      last_name: 'Narayana',
      email: 'lakshmi.narayana@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
      referred_by: 102,
    }, { // Storage, 50 locker availablity seeding
      id: 113,
      salutation: 'Mr',
      first_name: 'Darshan',
      last_name: 'V',
      email: 'darshn.v@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: 1,
    }, { // on ship Request Packaging, seeding box inventory
      id: 114,
      salutation: 'Mr',
      first_name: 'Swarop',
      last_name: 'Sathya',
      email: 'swaroop.m@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: OPS,
    }, { // Payment Approval
      id: 115,
      salutation: 'Mr',
      first_name: 'Manjunath',
      last_name: '',
      email: 'manjunath.k@shoppre.com',
      phone_code: '91',
      phone: '7891378913',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6', // admin1234
      group_id: FINANCE,
    }, { // -SALES
      id: 116,
      salutation: 'Mrs',
      first_name: 'Tanuja',
      last_name: 'P',
      email: 'tanuja.p@shoppre.com',
      phone_code: '91',
      phone: '9844717202',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: 2,
    }, {
      id: 738,
      salutation: 'Mrs',
      first_name: 'Vikas',
      last_name: 'Kumar',
      email: 'vikasjson@gmail.com',
      phone_code: '91',
      phone: '9634679754',
      password: '$2y$10$4Yg4RRg.HLMIpvd2L5nQO.vaRT.cW9NlsfXwi5alT1nKCa7dIs1R6',
      group_id: 2,
    },
    {
      id: 65,
      salutation: 'Mrs',
      first_name: 'Sheefa',
      last_name: 'Krishnakumar',
      email: 'sheefakk@gmail.com',
      phone_code: '',
      phone: '971',
      group_id: 2,
      password: '$2y$10$x5t2mMSfp3/uhW7u.9zu2.BDCoJmm.WkHbow0RkTgLYh3NIPBKJLG',
    }, {
      id: 207,
      salutation: 'Mrs',
      first_name: 'laila',
      last_name: 'elkarne',
      email: 'elkarne@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$dTz3tyel6f80KAX9sUyYQ.cR1y1PrqmYjNyXCbaGJq6hL8.G3t4c2',
    }, {
      id: 840,
      salutation: 'Mr',
      first_name: 'Vinay ',
      last_name: 'Kumar',
      email: 'vnkmr7423@gmail.com',
      phone_code: '1',
      phone: '8582269056',
      group_id: 2,
      password: '$2y$10$HZ7TbZNg973ZKPSamaz8u.TogJNWeTn1YEMfHqdFPhFhpg7v44Cce',
    }, {
      id: 1205,
      salutation: 'Mrs',
      first_name: 'Sushmitha',
      last_name: 'S',
      email: 'myjobs.sush@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$VEZsYN06bCeW6X9kWTt6ZO/ofJ7c/OazlNbV/iIDFh12MYqFusIZ2',
    }, {
      id: 1350,
      salutation: 'Mr',
      first_name: 'Nawsherwan',
      last_name: 'Mujtaba',
      email: 'nawsherwan786@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$oqbjNJSOthcfBr3vNtoGYehTIRl42.FqWodW6FD8SF7UVlbN9Q2VO',
    }, {
      id: 1390,
      salutation: 'Mrs',
      first_name: 'Vidula',
      last_name: 'Jamaloodeen',
      email: 'vidula27@hotmail.com',
      phone_code: '',
      phone: '23052571227',
      group_id: 2,
      password: '$2y$10$YbCSXIZ/KDxbUFRgeRhSs.QApnHJXswnXnvL7wygTNU5LNiVVNKSa',
    }, {
      id: 1599,
      salutation: 'Mrs',
      first_name: 'Lysander',
      last_name: '',
      email: 'lysander.fernandes@gmail.com',
      phone_code: '',
      phone: '9819586858',
      group_id: 2,
      password: '$2y$10$xwHNh5NKWIFAEPONPFJrnOjGaxNUMEGB5uixhi/aD/aJbMNDEj6AG',
    }, {
      id: 1610,
      salutation: 'Mr',
      first_name: 'Nishant ',
      last_name: 'Yadav',
      email: 'nishantyadav25@gmail.com',
      phone_code: '91',
      phone: '9035566011',
      group_id: 2,
      password: '$2y$10$wod5BON8EN3URhmuIHA8VuZlXuXnAzZg6k11xjUH5N3PQ3RXelGX2',
    }, {
      id: 1874,
      salutation: 'Mrs',
      first_name: 'Manju',
      last_name: 'Unnithan',
      email: 'manjuunnithan@gmail.com',
      phone_code: '44',
      phone: '7466714557',
      group_id: 2,
      password: '$2y$10$nz7cRD.DsmvH7As3uL9r5OxeHO3f9YeDZwSLnhvYX1XQGW3GyCPlu',
    }, {
      id: 1933,
      salutation: 'Mr',
      first_name: 'Abdulkader ',
      last_name: 'Kadernani',
      email: 'kadernani@yahoo.com',
      phone_code: '1',
      phone: '6047834765',
      group_id: 2,
      password: '$2y$10$cPr.xlJDEJw1GT9YpX2eXeP2oSVmngdOKJROefUj/5rGABEdTjq2W',
    }, {
      id: 1989,
      salutation: 'Mrs',
      first_name: 'Shilpa',
      last_name: 'Pandey',
      email: 'Shilpa.pandey@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$fROg4PrpzHNx7htf3kYkHulU6q3xzx19JoBukE.ryXUaWBo9Li.Di',
    }, {
      id: 1993,
      salutation: 'Mr',
      first_name: 'Anirudh',
      last_name: '',
      email: 'anirudh2727@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$PaD/JN7eQ8xlH9ONcPQq1u9xCWjg4abwfXuSQ126m/3WukAm7YNEe',
    }, {
      id: 2180,
      salutation: 'Mr',
      first_name: 'Varun ',
      last_name: 'Tandon',
      email: 'varun.tandon94@gmail.com',
      phone_code: '91',
      phone: '8527285259',
      group_id: 2,
      password: '$2y$10$WVA4tDihN9BqSQCT.1kJLujSy3I7WeBFXMasViabD5Y18lr5RT7CK',
    }, {
      id: 2253,
      salutation: 'Mr',
      first_name: 'Ivan ',
      last_name: 'Coinu',
      email: 'coinu.ivan@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$ivIbTdAM77xId18DAGeEGuuaN31Wvjsm3WGB3tPPrQGXwueFBEW.G',
    }, {
      id: 2977,
      salutation: 'Mr',
      first_name: 'Sudeep',
      last_name: 'Sagar',
      email: 'kpsudeepsagar@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$kvj7klHwAvkj4Hsv5YfCnudakljunWXrDYFtgsux2o4I507X3kK7y',
    }, {
      id: 3525,
      salutation: 'Mr',
      first_name: 'Vineel ',
      last_name: 'Danala',
      email: 'alwaysvineel@gmail.com',
      phone_code: '91',
      phone: '8904022334',
      group_id: 2,
      password: '$2y$10$9cnSB9N0IXyHxIRFBW1ayO7qpSuqukcfWnNziB7RIe1XC57HcpPYa',
    },
    {
      id: 104,
      salutation: 'Mrs',
      first_name: 'Supriya ',
      last_name: 'Biju',
      email: 'supriyamkn@gmail.com',
      phone_code: '',
      phone: '0',
      group_id: 2,
      password: '$2y$10$gRwrQB8pWKYxE387kUfc4OKTzrPrwoS1opBh.oHMJ5P0CEhsn3F2e',
    }, {
      id: 181,
      salutation: 'Mr',
      first_name: 'joseph',
      last_name: '',
      email: 'josephpulickan88@gmail.com',
      phone_code: '971',
      phone: '559793776',
      group_id: 2,
      password: '$2y$10$F3eBFVw0isO2iu/uxc8/Te/c9fV7MOurVuslmG8NGf5coV1S8iaDS',
    }, {
      id: 226,
      salutation: 'Mr',
      first_name: 'ABDULLA ',
      last_name: 'ZAFAR',
      email: 'zafarkp@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$eYDufnZUiKeMqoWuo9fno.xFGqo1SN5dG28pLKaNV.kkLPrqiDEH6',
    }, {
      id: 687,
      salutation: 'Mrs',
      first_name: 'Shamyla',
      last_name: '',
      email: 'shamyla.yusuf@gmail.com',
      phone_code: '971',
      phone: '508548955',
      group_id: 2,
      password: '$2y$10$Zjq1ACncC0iIbw3kjDRQ3./azyD7FYdSXYrq7lw80R1NTOQmb4oRC',
    }, {
      id: 948,
      salutation: 'Mrs',
      first_name: 'Nikkitha ',
      last_name: 'Shanker',
      email: 'niksfb3590@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 9,
      password: '$2y$10$FiGAwkP1ulS9kSFKS760ROZodS6gi0VwPSnpI5fuDwvAEWRT0f5D6',
    }, {
      id: 1029,
      salutation: 'Mrs',
      first_name: 'Ruchi ',
      last_name: 'Agarwal',
      email: 'ruchi.ruchiaries99@gmail.com',
      phone_code: '',
      phone: '',
      group_id: 2,
      password: '$2y$10$qoUhzJE2NHsPMQDZybpPD.2r/R8CGUbJEtXYy451ofaKkkrG19gnC',
    }, {
      id: 1102,
      salutation: 'Mrs',
      first_name: 'Syma ',
      last_name: 'Kazeminy',
      email: 'taxcafe@yahoo.com',
      phone_code: '1',
      phone: '4153682010',
      group_id: 2,
      password: '$2y$10$Lm8VTf4K2CnNaFnyXhfs7uYmyasoWTX7UJ5RhZwOo1gvrkw2NQfpi',
    }, {
      id: 2577,
      salutation: 'Mr',
      first_name: 'Rohit ',
      last_name: 'Menezes',
      email: 'rohit.menezes29@gmail.com',
      phone_code: '1',
      phone: '4379840257',
      group_id: 2,
      password: '$2y$10$e03kqua1Nl/Upk8R/FX1AeZ7wV7E9Z8ZMewn9R2lP2aLx8MFhNph2',
    },
  ].map(x => ({

    country_id: IND,
    ...x,
    profile_photo_url: 'https://lh3.googleusercontent.com/-UYCUQAneuQo/AAAAAAAAAAI/AAAAAAAAAAo/tGVHInxDmiY/photo.jpg?sz=50',
  }));
};
