
module.exports = () => [{
  name: 'Vineel Danala',
  source_id: 2,
  description: 'Representatives are really helpful and polite. Sorry I made one of your representatives wait for half an hour while picking up the package. Delivered the package to US within the timeline mentioned.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 3525,
  shipment_id: 736,
  country_id: 226,
},
{
  name: 'Varun Tandon',
  source_id: 2,
  description: 'Excellent service. My courier reached from Delhi to USA in 3 days, out of which one was a Sunday.\nEverything was perfect and I was assisted by Tanuja very politely and she explained me each and every nuance of it.\nAffordable price, and great service.\nKeep it up!',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 2180,
  shipment_id: 314,
  country_id: 226,
},
{
  name: 'Ahmad Jamaloodeen',
  source_id: 2,
  description: 'Vidula here, Excellent service!  the whole team is very nice and they help a lot.  I have dealt several times with Tanuja and she is just EXCELLENT!  prompt reply , always there to attend to any query and she knows how to reassure clients! she is very sweet and i would like to say customer service is 100% excellent!',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 1390,
  shipment_id: 424,
  country_id: 99,
},
{
  name: 'Aswathy Revi',
  source_id: 2,
  description: "Shoppre did a fantastic job in delivering a gift to my husband who is working in Doha, Qatar. Even though I was very skeptical about  their service in the beginning, I'm so glad that they proved me wrong!! Thank you Shoppre for your hassle free service! 😘",
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Sudeep Sagar',
  source_id: 2,
  description: 'Amazing and very fast service.They told me it would reach within 5 working days but it actually reached within 3 working days. \nI’m very much satisfied with Shoppre services.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 2977,
  shipment_id: 503,
  country_id: 224,
},
{
  name: 'Neethu George',
  source_id: 2,
  description: 'Great service! Excellent customer service and quality of shipment! Will definitely recommend to all!',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Sano Samuel',
  source_id: 2,
  description: 'Very professional, on time delivery, quality service. A must recommended service to get your favourite goodies from India sitting at any part of the globe..',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Ivan Coinu',
  source_id: 2,
  description: 'Very Good quality of support and shipment! Support team are always available, kindly and ready to give support by chat and by phone!\nMy california ship is arrived very soon and i am truly very satisfied!! Thank You!!!',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 2253,
  shipment_id: 337,
  country_id: 226,
},
{
  name: 'di yu',
  source_id: 2,
  description: "A really nice place where you can enjoy a first class shopping & shipping service. Thank you, Tanuja for your patient explanation, timely notification and your colleagues' diligence!!!",
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Meena Reddy',
  source_id: 2,
  description: 'Amazing, and very fast delivery service.  Highly recommend this shipping company! Thank you shoppre for your excellent service',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'anirudh lal',
  source_id: 2,
  description: 'Extremely reliable shipping/courier agents. Miss Tanuja who had continuously worked for my shipping to U.S, even after facing hiccups with Dhl, Tanuja had a secondary plan, and made the shipping happen. Shopree executive were in constant touch with the movement of package till the time it reached my consignee.\n\nThank you everyone at shopree',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 1993,
  shipment_id: 295,
  country_id: 226,
},
{
  name: 'Lysander Fernandes',
  source_id: 2,
  description: "Hands down, the most reliable service i could've used to send a 2.5kg package to the USA. It was a Drone i was shipping back to DJI, USA. Saneel - who is one of the relationship managers, ensured from the pick up to the the delivery - i was informed every step of the way. Will definitely use this service again and openly recommend. Package was delivered in 3 days. UPS was charging me 7.5k for the same package. Shoppre used FEdex to deliver. Haha UPS. You lose business...AGAIN. Thank you Shoppre. You guys are Awesome",
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 1599,
  shipment_id: 262,
  country_id: 226,
},
{
  name: 'Nishant Yadav',
  source_id: 2,
  description: 'Important feedback at the end. Well, it was my first experience of an international courier to my GF in the USA and I was really confused with all the import laws and furious with the price that was being asked by big courier companies. After searching a lot on Google I came across this startup and to be honest I was really skeptical as their quoted price was half of what everyone else was asking. For next few days, I called their office with many doubts and queries and every time Mr. Saneel was really-really friendly and helpful. Still, I was not convinced as I thought it was some kind of scam, so I decided to visit their office(even though they had a home pickup option). Some renovation was going on at their office but still, I chose to trust Mr. Saneel and left my box at their office. From there on everything went smooth as they kept my box in the locker because I ordered some sweets from Jodhpur and it was delayed. They gave me an address to reroute my sweets packets directly to their office and once it was received they packed the entire box and I was given a DHL courier receipt as promised, Not just that but Mr. Saneel was even kind enough to purchase one small pooja item for me as I forgot to put it in the box and it was very important for her. During whole time they kept me updated via WhatsApp and needless to say that my courier was well received within 5 days including the weekend. Overall I am 100% satisfied with the customer support, service and needless to say their price is unbeatable.\nFEEDBACK:  Kindly add a proper payment gateway like visa/MasterCard or even net banking. The only payment option available right now is either via Paytm or your bank account numbers which is neither professional nor trustworthy for a new customer. Even I had the problem with this payment system like some others as even my payment via Paytm gateway was not processed timely. I wanted to give you guys 3 or 4 stars just because of this payment issue but I still went with 5-star as the support and service provided by Mr. Saneel during the whole process were wonderful.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 1610,
  shipment_id: 207,
  country_id: 226,
},
{
  name: 'Alyssa Siddiqui',
  source_id: 2,
  description: 'Exceptional, amazing, and very fast service.  Highly recommend this shipping company!  I wanted to order an item in India and shipped to the US, but I did not have an Indian credit card.  They had their "personal shopper" purchase the item and shipped to the US.  They give you updates throughout the process and there was a good amount of communication throughout.  Their pricing and service is also quoted very well.  I will definitely recommend them to everyone I know and will use this service again soon.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Vinay Kumar',
  source_id: 2,
  description: 'A great choice for International Shipping, they are prompt, accurate and top of the line courier service backed by exceptional customer support. Shopping made real easy. Amazing option!',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 840,
  shipment_id: 149,
  country_id: 226,
},
{
  name: 'Sushmitha S',
  source_id: 2,
  description: 'The website is not fully functional. Payment was not thru site and was asked to do to some a/c no which was very unprofessional. Invoice was sent only a day before the item was delivered. Everytime to check the status I had to call and ask as that was not updated in their site against my order. This package would have delivered in 3-4 days thru other service, here it took 2 weeks. So overall I was unhappy with the service.',
  rating: 1,
  is_approved: '',
  approved_by: '',
  customer_id: 1205,
  shipment_id: 102,
  country_id: 38,
},
{
  name: 'darshan raj',
  source_id: 2,
  description: 'I was very happy with the service. Trust worthy :)',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Dhananjaya S',
  source_id: 2,
  description: 'Trust worthy  and fastest  service. Thank you shoppre',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Nawsherwan Mujtaba',
  source_id: 2,
  description: "Imagine sending a gift and the birthday person has to pay $30 to get the gift. How embarrassing it is. False promises and when asked why, they said, don't know why!  Very unprofessional.",
  rating: 1,
  is_approved: '',
  approved_by: '',
  customer_id: 1350,
  shipment_id: 133,
  country_id: 38,
},
{
  name: 'Abdulkader Kadernani',
  source_id: 2,
  description: 'rough each Genuine parcel forwarding service that acts as your personal concierge! They guide you and help you at every step. Sad we cannot rate higher than 5 stars...they deserve a lot more!',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 1933,
  shipment_id: 304,
  country_id: 226,
},
{
  name: 'Sudhakar Babu DS',
  source_id: 2,
  description: 'Prompt delivery. Great customer support. Saved at least Rs 2000 over my 1 Kg consignment, where others have quoted Rs 3800 to Rs 6100 for the same.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Venu gopal',
  source_id: 2,
  description: 'Excellent service & shipping charges are very affordable compare to others...',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Sheefa KrishnaKumar',
  source_id: 2,
  description: 'Excelent service...Great help for all NRI shoppers...\nPrompt Delivery in nominal rate. A trustworthy locker for our valuable online purchases.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 65,
  shipment_id: 723,
  country_id: 224,
},
{
  name: 'Aswathi Sudhir',
  source_id: 2,
  description: 'The best service ever!!  Shoppre notified me of the status of each and every item that I ordered. Packed and sent all items with great care at great price!! I would recommend it to all :)',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Nakul Chandra',
  source_id: 2,
  description: 'They are providing awesome services with very cost effective rates & on time delivery. I would say responsible shipping company.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Manju unnithan',
  source_id: 2,
  description: 'Excellent service,Prompt delivery(earlier than expected),Great customer support and assistance,Strongly recommended',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 1874,
  shipment_id: 266,
  country_id: 225,
},
{
  name: 'amit jain',
  source_id: 2,
  description: 'Great service. The parcel was at my house within five days from the despatch in India. No customs problem faced. They keep you updated with every development with your shipment. I was shared the pics of the products before despatch. Overall fully satisfied service. The rates are also quite competitive even for lesser volume.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'varun murali',
  source_id: 2,
  description: '5 stars I am giving because of the communication,notifications;on time support, special care packaging and the  most important thing that we all look for is the affordable pricing for the shipping charges that does not break your wallet.their team members also helped by sending me photos of the products that I got which I bought online.in this way you will know  the products are same that you shopped online in terms of colour ,size and design and also one feature is that they could do personal shopper for you as well.if you want something then you can ask them to shop for you.this is overall a great service which I highly recommend to anyone who wants shop online and get it fast with affordable budget.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 129,
  shipment_id: 479,
  country_id: 224,
},
{
  name: 'Manish Panchal',
  source_id: 2,
  description: 'they were super helpful! I was in a rush and had to send my parcel quickly to USA, they got everything done so quickly and were so polite and seemed like genuinely happy people. they have great service and good pricie. Received parcel before time.\nI would strongly recommend SHOPPRE for sending parcel between India and other countries.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Jeroen Pl',
  source_id: 2,
  description: "Actually, cheaper and better than I expected. Shoppre provides regular status updates, shows pictures of received items, and have a good response time on Whatsapp, Facebook Messenger and email. Forwarded mail comes with track&trace. Don't be put off by the (for now) small oddities on their website.",
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Amit Kumar',
  source_id: 2,
  description: 'Excellent service......... & shipping charges are very less compare to others........',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Arun Prem',
  source_id: 2,
  description: 'Quick and professional service. Both in terms of delivery and customer relations. Highly recommend for hassle free shipping experience.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Sruthi Menon',
  source_id: 2,
  description: 'Amazing service. Extremely happy with their speed in delivery. ☺️',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Mukesh Gorai',
  source_id: 2,
  description: 'Amazing,and shipping charges very less.and very fast delivery...............',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Kishore Reddy',
  source_id: 2,
  description: 'Excellent  & very less price  and fast delivery.....',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'ALOAK JAWALI',
  source_id: 2,
  description: 'Highly recommend, affordable shipping price worldwide, fast response and good customer service!!',
  rating: 4,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Nakul Glorywebs',
  source_id: 2,
  description: 'Excellent  & very less price  and fast delivery.....',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'divya kumar',
  source_id: 2,
  description: 'Spot on service. Anyone ever in need of receiving items bought online from indian sites , would never regret using shoppre service.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'abhijeeth shanker',
  source_id: 2,
  description: 'Reliable and fast.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Innira Saneel',
  source_id: 2,
  description: 'Best and reliable :)',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Rohith Kumar',
  source_id: 2,
  description: 'nice service',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Sharath lal',
  source_id: 2,
  description: 'Very efficient,fast and hassle free.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Ravi Kumar Kola',
  source_id: 2,
  description: 'Very satisfied with the service.',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Laila el karne',
  source_id: 2,
  description: "(Translated by Google) I thank the shoppre team to help and support that Mount door early, really very fast very organized and very punctual. they have taken care to pay the site from their account and delivery and the parcel was delivered in 4 days until the house\n\n## I would like to thank the team of shoppre for the help and the accompaniment goes qui From The Beginning, really has very fast service very Organized and very punctual. They Took care of paying the website from Their accounts and delivery, so the package Was Delivered Within 4 days to the house\n\nThank you for all the team\n\n(Original)\nje voudrais remercier l’équipe de shoppre pour l'aide et l'accompagnement qui mont porte de le début , vraiment un service très rapide très organiser et très ponctuel . ils ont pris en charge de payer le site depuis leur compte et de la livraison , ainsi le colis était livrer dans 4 jours jusqu’à la maison \n\n##I would like to thank the team of shoppre for the help and the accompaniment which goes from the beginning, really a very fast service very organized and very punctual. they took charge of paying the site from their accounts and delivery, so the package was delivered within 4 days to the house\n\nThank you for all the team",
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 207,
  shipment_id: 373,
  country_id: 144,
},
{
  name: 'Million Designs',
  source_id: 2,
  description: '',
  rating: 3,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Shinu A Habeeb',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Sinu Moosa',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'ashy abraham',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'vinai raj',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Shilpa Pandey',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: 1989,
  shipment_id: 267,
  country_id: 226,
},
{
  name: 'Shafeeq Khan',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Manjesh Vinayaka',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Vishnu Prabhu',
  source_id: 2,
  description: '',
  rating: 2,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'harshel jain',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'vismaya rk',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Grince Mathew',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Dhruv Prajapati',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
{
  name: 'Sikander Kumar',
  source_id: 2,
  description: '',
  rating: 5,
  is_approved: '',
  approved_by: '',
  customer_id: '',
  shipment_id: '',
  country_id: '',
},
];
