
module.exports = () => [{
  name: 'Varun Tandon',
  source_id: 2,
  description: 'Excellent service. My courier reached from Delhi to USA in 3 days, out of which one was a Sunday.\nEverything was perfect and I was assisted by Tanuja very politely and she explained me each and every nuance of it.\nAffordable price, and great service.\nKeep it up!',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 2180,
  shipment_id: 314,
  country_id: 226,
},
{
  name: 'Ahmad Jamaloodeen',
  source_id: 2,
  description: 'Vidula here, Excellent service!  the whole team is very nice and they help a lot.  I have dealt several times with Tanuja and she is just EXCELLENT!  prompt reply , always there to attend to any query and she knows how to reassure clients! she is very sweet and i would like to say customer service is 100% excellent!',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 1390,
  shipment_id: 424,
  country_id: 99,
},
{
  name: 'Aswathy Revi',
  source_id: 2,
  description: "Shoppre did a fantastic job in delivering a gift to my husband who is working in Doha, Qatar. Even though I was very skeptical about  their service in the beginning, I'm so glad that they proved me wrong!! Thank you Shoppre for your hassle free service! 😘",
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'Sudeep Sagar',
  source_id: 2,
  description: 'Amazing and very fast service.They told me it would reach within 5 working days but it actually reached within 3 working days. \nI’m very much satisfied with Shoppre services.',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 2977,
  shipment_id: 503,
  country_id: 224,
},
{
  name: 'Neethu George',
  source_id: 2,
  description: 'Great service! Excellent customer service and quality of shipment! Will definitely recommend to all!',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'Sano Samuel',
  source_id: 2,
  description: 'Very professional, on time delivery, quality service. A must recommended service to get your favourite goodies from India sitting at any part of the globe..',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'Ivan Coinu',
  source_id: 2,
  description: 'Very Good quality of support and shipment! Support team are always available, kindly and ready to give support by chat and by phone!\nMy california ship is arrived very soon and i am truly very satisfied!! Thank You!!!',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 2253,
  shipment_id: 337,
  country_id: 226,
},
{
  name: 'di yu',
  source_id: 2,
  description: "A really nice place where you can enjoy a first class shopping & shipping service. Thank you, Tanuja for your patient explanation, timely notification and your colleagues' diligence!!!",
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'Meena Reddy',
  source_id: 2,
  description: 'Amazing, and very fast delivery service.  Highly recommend this shipping company! Thank you shoppre for your excellent service',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'anirudh lal',
  source_id: 2,
  description: 'Extremely reliable shipping/courier agents. Miss Tanuja who had continuously worked for my shipping to U.S, even after facing hiccups with Dhl, Tanuja had a secondary plan, and made the shipping happen. Shopree executive were in constant touch with the movement of package till the time it reached my consignee.\n\nThank you everyone at shopree',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 1993,
  shipment_id: 295,
  country_id: 226,
},
{
  name: 'Lysander Fernandes',
  source_id: 2,
  description: "Hands down, the most reliable service i could've used to send a 2.5kg package to the USA. It was a Drone i was shipping back to DJI, USA. Saneel - who is one of the relationship managers, ensured from the pick up to the the delivery - i was informed every step of the way. Will definitely use this service again and openly recommend. Package was delivered in 3 days. UPS was charging me 7.5k for the same package. Shoppre used FEdex to deliver. Haha UPS. You lose business...AGAIN. Thank you Shoppre. You guys are Awesome",
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 1599,
  shipment_id: 262,
  country_id: 226,
},
{
  name: 'Nishant Yadav',
  source_id: 2,
  description: 'Important feedback at the end. Well, it was my first experience of an international courier to my GF in the USA and I was really confused with all the import laws and furious with the price that was being asked by big courier companies. After searching a lot on Google I came across this startup and to be honest I was really skeptical as their quoted price was half of what everyone else was asking. For next few days, I called their office with many doubts and queries and every time Mr. Saneel was really-really friendly and helpful. Still, I was not convinced as I thought it was some kind of scam, so I decided to visit their office(even though they had a home pickup option). Some renovation was going on at their office but still, I chose to trust Mr. Saneel and left my box at their office. From there on everything went smooth as they kept my box in the locker because I ordered some sweets from Jodhpur and it was delayed. They gave me an address to reroute my sweets packets directly to their office and once it was received they packed the entire box and I was given a DHL courier receipt as promised, Not just that but Mr. Saneel was even kind enough to purchase one small pooja item for me as I forgot to put it in the box and it was very important for her. During whole time they kept me updated via WhatsApp and needless to say that my courier was well received within 5 days including the weekend. Overall I am 100% satisfied with the customer support, service and needless to say their price is unbeatable.\nFEEDBACK:  Kindly add a proper payment gateway like visa/MasterCard or even net banking. The only payment option available right now is either via Paytm or your bank account numbers which is neither professional nor trustworthy for a new customer. Even I had the problem with this payment system like some others as even my payment via Paytm gateway was not processed timely. I wanted to give you guys 3 or 4 stars just because of this payment issue but I still went with 5-star as the support and service provided by Mr. Saneel during the whole process were wonderful.',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 1610,
  shipment_id: 207,
  country_id: 226,
},
{
  name: 'Alyssa Siddiqui',
  source_id: 2,
  description: 'Exceptional, amazing, and very fast service.  Highly recommend this shipping company!  I wanted to order an item in India and shipped to the US, but I did not have an Indian credit card.  They had their "personal shopper" purchase the item and shipped to the US.  They give you updates throughout the process and there was a good amount of communication throughout.  Their pricing and service is also quoted very well.  I will definitely recommend them to everyone I know and will use this service again soon.',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'Vinay Kumar',
  source_id: 2,
  description: 'A great choice for International Shipping, they are prompt, accurate and top of the line courier service backed by exceptional customer support. Shopping made real easy. Amazing option!',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: 840,
  shipment_id: 149,
  country_id: 226,
},
{
  name: 'Sushmitha S',
  source_id: 2,
  description: 'The website is not fully functional. Payment was not thru site and was asked to do to some a/c no which was very unprofessional. Invoice was sent only a day before the item was delivered. Everytime to check the status I had to call and ask as that was not updated in their site against my order. This package would have delivered in 3-4 days thru other service, here it took 2 weeks. So overall I was unhappy with the service.',
  rating: 1,
  is_approved: 1,
  approved_by: null,
  customer_id: 1205,
  shipment_id: 102,
  country_id: 38,
},
{
  name: 'darshan raj',
  source_id: 2,
  description: 'I was very happy with the service. Trust worthy :)',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'Dhananjaya S',
  source_id: 2,
  description: 'Trust worthy  and fastest  service. Thank you shoppre',
  rating: 5,
  is_approved: 1,
  approved_by: null,
  customer_id: null,
  shipment_id: null,
  country_id: null,
},
{
  name: 'Nawsherwan Mujtaba',
  source_id: 2,
  description: "Imagine sending a gift and the birthday person has to pay $30 to get the gift. How embarrassing it is. False promises and when asked why, they said, don't know why!  Very unprofessional.",
  rating: 1,
  is_approved: 1,
  approved_by: null,
  customer_id: 1350,
  shipment_id: 133,
  country_id: 38,
},
{
  name: 'Abdulkader Kadernani',
  source_id: 2,
  description: 'rough each Genuine parcel forwarding service that acts as your personal concierge! They guide you and help you at every step. Sad we cannot rate higher than 5 stars...they deserve a lot more!',
  rating: 5,
  is_approved: true,
  approved_by: 1,
  customer_id: 129,
  shipment_id: 115,
}];
