const viewConfig = require('../../../../emails/config');

const packageItems = [{
  id: 9,
  name: 'Hello Box',
  quantity: 2,
  price_amount: 2,
  total_amount: 4,
  object: 'https://staging-cdn.shoppre.com/shoppre/2018/6/8a854b15-7cc5-4553-b8ae-a6fd49fe89ee.png',
  package_item_category_id: 18,
  PackageItemCategory: {
    name: 'Good Category',
  },
  package_id: '10',
  created_by: 1,
}];

const OPS = {
  first_name: 'Saneel',
  last_name: 'E S',
  email: 'support@shoppre.com',
};

const pkg = {
  id: 1,
  invoice_code: 'AMZ123',
  Store: {
    name: 'Amazon',
  },
};

const customer = {
  name: 'Mr. Abhinav Mishra',
  first_name: 'Abhinav',
  virtual_address_code: 'SHPR12-182',
  email: 'support@shoppre.com',
};

const ENV = viewConfig;

module.exports = {
  PACKAGE_ITEMS_UPLOAD_PENDING: {
    PACKAGE_ITEMS_UPLOAD_PENDING: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
  },
  CUSTOMER_INPUT: {
    CUSTOMER_INPUT: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  READY_TO_SHIP: {
    READY_TO_SHIP: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  DAMAGED: {
    DAMAGED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  RETURN_REQUEST_FROM_CUSTOMER: {
    RETURN_REQUEST_FROM_CUSTOMER: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  RETURN_PICKUP_DONE: {
    RETURN_PICKUP_DONE: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  SPLIT_PACKAGE: {
    SPLIT_PACKAGE: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  SPLIT_PACKAGE_PROCESSED: {
    SPLIT_PACKAGE_PROCESSED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  DISCARDED: {
    DISCARDED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  DISCARD_REQUESTED: {
    DISCARD_REQUESTED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  STANDARD_PHOTO_REQUEST: {
    STANDARD_PHOTO_REQUEST: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  ADVANCED_PHOTO_REQUEST: {
    ADVANCED_PHOTO_REQUEST: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  PS_RETURN_REQUESTED: {
    PS_RETURN_REQUESTED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  PS_REFUND_RECIEVED: {
    PS_REFUND_RECIEVED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  ORDER_CREATED: {
    ORDER_CREATED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  ORDER_CANCELLED: {
    ORDER_CANCELLED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  PAYMENT_INITIATED: {
    PAYMENT_INITIATED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  PAYMENT_FAILED: {
    PAYMENT_FAILED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  PAYMENT_COMPLETED: {
    PAYMENT_COMPLETED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  ORDER_PLACED: {
    ORDER_PLACED: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  OUT_OF_STOCK: {
    OUT_OF_STOCK: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  REFUNDED_TO_WALLET: {
    REFUNDED_TO_WALLET: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  REFUNDED_TO_BANK_ACCOUNT: {
    REFUNDED_TO_BANK_ACCOUNT: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
  AWAITING_PACKAGE: {
    AWAITING_PACKAGE: true,
    pkg,
    customer,
    actingUser: OPS,
    ENV,
    packageItems,
  },
};
